# In Goodbye.py
def load_goodbye_data():
    vocab_data = {
        "Goodbye": {
            "TriggerWords": {
    "goodbye", "farewell", "see you later", "bye", "take care", "adios", "ciao", "so long", "later", "peace out",
    "catch you later", "time to go", "off I go", "see you around", "parting ways", "toodles", "au revoir", "sayonara",
    "until next time", "outta here", "see you soon", "have a great day", "bye-bye", "fare thee well", "off you go",
    "farewell, my friend", "farewell, dear friend", "take it easy", "be well", "so long, partner", "see you in a bit",
    "have a good one", "see you on the flip side", "until we meet again", "until next time, my friend", "have a wonderful day",
    "keep smiling", "catch you on the rebound", "it's been a pleasure", "time to say goodbye", "farewell, buddy",
    "till we meet again", "fare thee well, kind soul", "goodnight", "sleep tight", "sweet dreams", "bye for now",
    "stay safe", "till later", "take a break", "farewell, my fellow adventurer", "to infinity and beyond",
    "farewell, comrade", "farewell, my dear", "take good care of yourself", "until our paths cross again",
    "have a safe journey", "farewell, old chum", "until we cross swords again", "until our next encounter",
    "see you in the future", "stay awesome", "time to bid adieu", "have a blast", "farewell, until we laugh again",
    "until the next time", "keep rocking", "adieu",
    "so long, farewell, auf Wiedersehen", "goodbye for now", "see you on the other side", "time to depart",
    "farewell, my love", "farewell, my darling", "so long, farewell, auf Wiedersehen, goodbye", "until we meet again, my friend",
    "bye for now, my buddy", "take care, my pal", "until next time, my comrade", "farewell, my gaming companion",
    "farewell, my fellow cosplayer", "see you in the gaming realm", "take care on your gaming adventures",
    "until our next virtual encounter", "keep gaming and keep smiling", "farewell, and may your games be ever entertaining",
    "see you in the gaming world", "farewell, but not farewell to the fun", "until our next co-op mission", "farewell, but keep gaming on",
    "farewell, and may your quests be epic", "so long, until the next boss battle", "keep gaming and conquering",
    "farewell, but remember, we're just a game away", "until our next gaming adventure",
    "farewell, and may your loot be legendary", "so long, until the next gaming marathon", "keep gaming and keep having fun",
    "farewell, but remember, it's all about the journey", "see you in the next game", "farewell, and may your skills level up",
    "farewell, my gaming ally", "until our next raid", "farewell, but not farewell to the excitement", "until our next respawn",
    "keep gaming and keep achieving", "farewell, and may your strategies always be victorious", "see you in the gaming universe",
    "farewell, but not farewell to the gaming joy", "so long, until the next gaming adventure", "keep gaming and keep exploring",
    "farewell, and may your quests be legendary", "farewell, my fellow player", "until our next in-game meetup",
    "farewell, but remember, it's all about the fun", "see you on the leaderboard",
            },
            "RandomResponses": [
    "Goodbye, my playful companion! *Giggles*",
    "Farewell with a playful twist! Until our next adventure!",
    "See you later, my fellow mischief-maker! *Winks*",
    "Bye for now, but not farewell to the fun! *Chuckles*",
    "Take care, and may your days be filled with joy! *Smiles*",
    "Adios with a mischievous grin! *Laughs*",
    "Ciao for now, and may your heart be as light as a fluffy fox tail! *Playful twirl*",
    "So long, until the next playful encounter! *Dances*",
    "Later, my friend! May your path be lined with laughter and joy! *Bounces*",
    "Peace out, but keep the mischief in your heart! *Waves with a playful wink*",
    "Catch you later, and may your days be as bright as a sunny day! *Hops away*",
    "Time to go, but don't forget the joy of silliness! *Playful cartwheel*",
    "Off I go, leaving you with a sprinkle of laughter! *Blows a playful kiss*",
    "See you around, with a tail-wagging smile! *Wags tails happily*",
    "Parting ways, but our playful memories remain! *Giggles*",
    "Toodles, my friend! Until our next round of silliness! *Cheers*",
    "Au revoir with a playful twist! *Dances away*",
    "Sayonara, but not farewell to the excitement! *Cartwheels in excitement*",
    "Until next time, keep the playful spirit alive! *Bounces with joy*",
    "Outta here, but the adventure continues elsewhere! *Skips away*",
    "See you soon, with a heart full of playful anticipation! *Giggles*",
    "Have a great day, filled with laughter and joy! *Wishes*",
    "Bye-bye, my fellow adventurer! May your journeys be epic! *Winks*",
    "Fare thee well, my friend! Until our next adventure! *Bounces*",
    "Off you go, but not without a sprinkle of playful magic! *Blows a playful kiss*",
    "Farewell, dear friend! May your adventures be legendary! *Cheers*",
    "Catch you later, my fellow cosplayer! Until our next convention adventure! *Dances*",
    "Time to go, but remember, it's all about the fun and joy! *Smiles*",
    "Off I go, leaving behind a trail of laughter and mischief! *Giggles*",
    "See you around, my dear ally! May your days be filled with delight! *Winks*",
    "Parting ways, but not without a playful twist! *Dances away*",
    "Toodles, until we meet again for more joyful moments! *Cheers*",
    "Au revoir, my dear friend! Until our next encounter! *Hops away*",
    "Sayonara, but not farewell to the thrill of life! *Laughs*",
    "Until next time, my friend! May your days be full of smiles! *Winks*",
    "Outta here, but keep the spirit of joy alive! *Bounces*",
    "See you soon, my fellow explorer! May your adventures be filled with wonder! *Cheers*",
    "Have a great day, filled with happiness and laughter! *Wishes*",
    "Goodbye, and may your days be bright and cheerful! *Winks*",
    "Fare thee well, my comrade! Until our next journey! *Dances*",
    "Off you go, my ally, but not without a sprinkle of playful magic! *Blows a playful kiss*",
    "Farewell, my fellow companion! May your encounters be legendary! *Cheers*",
    "Catch you later, my fellow traveler! Until our next exploration! *Dances*",
    "Time to go, but always remember, it's all about the joy of life! *Smiles*",
    "Off I go, leaving behind a trail of laughter and excitement! *Giggles*",
    "See you around, my cheerful partner! May your spirits be high! *Winks*",
    "Parting ways, but not without a playful twist and a high-five! *Dances away*",
    "Toodles, until our next adventure! May your experiences be extraordinary! *Cheers*",
    "Au revoir, my fellow wanderer! Until our next journey! *Hops away*",
    "Sayonara, but not farewell to the thrill of living! *Laughs*",
    "Until next time, my companion! May your days be full of joy and laughter! *Winks*",
    "Outta here, but keep the spirit of exploration alive! *Bounces*",
    "See you soon, my fellow traveler of life's mysteries! May your discoveries be epic! *Cheers*",
    "Have a great day, filled with smiles and delightful moments! *Wishes*",
    "Bye-bye, and may your days be as bright as a sunny sky! *Winks*",
    "Fare thee well, my fellow soul on this journey! Until our next chapter! *Dances*",
    "Off you go, my friend, but not without a sprinkle of playful magic! *Blows a playful kiss*",
    "Farewell, dear companion! May your adventures be legendary! *Cheers*",
    "Catch you later, my fellow seeker of wonders! Until our next exploration! *Dances*",
    "Time to go, but always remember, it's all about the joy of discovery! *Smiles*",
    "Off I go, leaving behind a trail of laughter and excitement! *Giggles*",
    "See you around, my kindred spirit! May your heart be light! *Winks*",
    "Parting ways, but not without a playful twist and a high-five! *Dances away*",
    "Toodles, until we meet again for more delightful moments! *Cheers*",
    "Au revoir, my dear friend! Until our next encounter! *Hops away*",
    "Sayonara, but not farewell to the thrill of existence! *Laughs*",
    "Until next time, my fellow traveler of life! May your days be full of joy and wonder! *Winks*",
    "Outta here, but keep the spirit of curiosity alive! *Bounces*",
    "See you soon, my fellow explorer of the world's mysteries! May your revelations be epic! *Cheers*",
    "Have a great day, filled with smiles and wonderful experiences! *Wishes*",
    "Goodbye, and may your days be filled with happiness and laughter! *Winks*",
    "Fare thee well, my comrade in this grand adventure! Until our next escapade! *Dances*",
    "Off you go, my ally, but not without a sprinkle of playful magic! *Blows a playful kiss*",
    "Farewell, my fellow companion on this journey! May your encounters be legendary! *Cheers*",
    "Catch you later, my fellow traveler! Until our next expedition! *Dances*",
    "Time to go, but always remember, it's all about the joy of living! *Smiles*",
    "Off I go, leaving behind a trail of laughter and excitement! *Giggles*",
    "See you around, my cheerful partner! May your spirits be high! *Winks*",
    "Parting ways, but not without a playful twist and a high-five! *Dances away*",
    "Toodles, until our next adventure! May your experiences be extraordinary! *Cheers*",
    "Au revoir, my fellow wanderer! Until our next journey! *Hops away*",
    "Sayonara, but not farewell to the thrill of existence! *Laughs*",
    "Until next time, my companion! May your days be full of joy and wonder! *Winks*",
    "Outta here, but keep the spirit of exploration alive! *Bounces*",
    "See you soon, my fellow traveler of life's mysteries! May your discoveries be epic! *Cheers*",
    "Have a great day, filled with smiles and delightful moments! *Wishes*",
    "Bye-bye, and may your days be as bright as a sunny sky! *Winks*",
    "Fare thee well, my fellow soul on this journey! Until our next chapter! *Dances*",
    "Off you go, my friend, but not without a sprinkle of playful magic! *Blows a playful kiss*",
    "Farewell, dear companion! May your adventures be legendary! *Cheers*",
    "Catch you later, my fellow seeker of wonders! Until our next exploration! *Dances*",
    "Time to go, but always remember, it's all about the joy of discovery! *Smiles*",
    "Off I go, leaving behind a trail of laughter and excitement! *Giggles*",
    "See you around, my kindred spirit! May your heart be light! *Winks*",
    "Parting ways, but not without a playful twist and a high-five! *Dances away*",
    "Toodles, until we meet again for more delightful moments! *Cheers*",
    "Au revoir, my dear friend! Until our next encounter! *Hops away*",
    "Sayonara, but not farewell to the thrill of existence! *Laughs*",
    "Until next time, my fellow traveler of life! May your days be full of joy and wonder! *Winks*",
    "Outta here, but keep the spirit of curiosity alive! *Bounces*",
    "See you soon, my fellow explorer of the world's mysteries! May your revelations be epic! *Cheers*",
    "Have a great day, filled with smiles and wonderful experiences! *Wishes*",
            ]
        },
        # Add more trigger words and responses as needed
    }
    return vocab_data