# In JPFLore.py

def load_jpflore_data():
    vocab_data = {
        "JPFolklore": {
            "TriggerWords": {
        "kitsune": "Kitsune, the clever shape-shifters, are a beloved part of Japanese folklore.",
        "kappa": "The kappa is known for its love of cucumbers and its tricky nature. Quite the character!",
        "tengu": "Tengu, with their long noses and martial arts skills, are fascinating beings in Japanese mythology.",
        "yokai": "Yokai, the supernatural creatures, add a touch of mystery to Japanese folklore.",
        "oni": "Oni, the ogre-like demons, are common figures in Japanese folklore, often depicted with horns and clubs.",
        "tsukumogami": "Tsukumogami are everyday objects that gain their own spirits after a century. It's a unique concept in Japanese mythology.",
        "jorogumo": "Jorogumo, the spider yokai known for its beautiful appearance and deadly intentions, is a captivating creature.",
        "rokurokubi": "Rokurokubi, the creatures with the ability to stretch their necks at night, are both spooky and intriguing.",
        "tannuki": "Tannuki are shape-shifters known for their mischievousness. They can turn leaves into gold or even transform into humans!",
        "yurei": "Yurei, the restless spirits of the dead, haunt the living in many eerie tales.",
        "amabie": "Amabie, a yokai resembling a mermaid-bird, is said to bring protection and health. An interesting figure from Japanese folklore.",
        "rokurokubi": "Rokurokubi, the creatures with the ability to stretch their necks at night, are both spooky and intriguing.",
        "noppera-bo": "Noppera-bo, the faceless ghost, is a common character in Japanese ghost stories.",
        "kasa-obake": "Kasa-obake, the umbrella yokai, is known for its animated behavior and one-legged stance.",
        "itako": "Itako, blind female mediums, are believed to have the ability to communicate with the dead.",
        "yuki-onna": "Yuki-onna, the snow woman, is a chilling figure associated with winter and cold climates.",
        "yamata-no-orochi": "Yamata-no-Orochi, the eight-headed serpent, is a legendary creature defeated by the hero Susanoo.",
        "momotaro": "Momotaro, the Peach Boy, is a heroic figure known for his journey to defeat oni and demons.",
        "urashima taro": "Urashima Taro's story of the Dragon Palace beneath the sea is a classic tale of adventure and timelessness.",
        "kintaro": "Kintaro, the 'Golden Boy,' is a beloved folk hero known for his incredible strength and bravery.",
        "tale of the bamboo cutter": "The Tale of the Bamboo Cutter tells the enchanting story of Kaguya-hime, the Moon Princess.",
        "kaguya-hime": "Kaguya-hime, the Moon Princess, is a central character in Japanese folklore with a captivating narrative.",
        "tamamo-no-mae": "Tamamo-no-Mae, a cunning kitsune spirit, played a significant role in Japanese history and legend.",
        "genji-monogatari": "Genji Monogatari, the Tale of Genji, is considered one of the world's first novels, filled with courtly romance and intrigue.",
        "tsuruya no hime": "Tsuruya no Hime, a legendary beauty, has captivated the hearts of many in traditional Japanese literature.",
        "shinigami": "Shinigami, the death spirits, are a part of Japanese folklore's dark and mysterious side.",
        "tengu": "Tengu, with their long noses and martial arts skills, are fascinating beings in Japanese mythology.",
        "satori": "Satori, the mind-reading creatures, are known for their psychic abilities and love for tofu.",
        "kuchisake-onna": "Kuchisake-onna, the slit-mouthed woman, is a chilling urban legend that still haunts the streets of Japan.",
        "zashiki-warashi": "Zashiki-warashi are childlike spirits believed to bring good fortune and protect households.",
        "abumi-guchi": "Abumi-guchi, a furry critter hiding in wells, is known for its mischievousness.",
        "teke-teke": "Teke-teke, the ghostly figure with a torso that makes a 'teke-teke' sound as it moves, is sure to send shivers down your spine.",
        "iwate-granite-beast": "The Iwate Granite Beast is a mysterious creature believed to reside in the mountains of Iwate Prefecture.",
        "gasha-dokuro": "Gasha-dokuro, the giant skeletal yokai made from the bones of the dead, is a terrifying sight.",
        "aobozu": "Aobozu, the blue monk, is a forest-dwelling yokai that can lead travelers astray.",
        "sodehiki-kozo": "Sodehiki-kozo, the sleeve-pulling boy, is known for tugging on people's sleeves at night, startling them.",
        "rashomon": "Rashomon, a gate in Kyoto, is the setting for a famous story of a demon and a samurai.",
        "gashadokuro": "Gashadokuro, the giant skeleton yokai, is said to appear during times of war and famine.",
        "amabie": "Amabie, a yokai resembling a mermaid-bird, is said to bring protection and health. An interesting figure from Japanese folklore.",
        "umibozu": "The Umibozu, a sea spirit that capsizes ships, adds an element of danger to maritime tales.",
        "jorogumo": "Jorogumo, the spider yokai known for its beautiful appearance and deadly intentions, is a captivating creature.",
        "futakuchi-onna": "Futakuchi-onna, with two mouths, is a grotesque but fascinating yokai.",
        "shichinin misaki": "Shichinin misaki, the Seven Ghostly Bridges, is a mysterious and eerie phenomenon in Japan.",
        "yurei": "Yurei, the restless spirits of the dead, haunt the living in many eerie tales.",
        "kamaitachi": "Kamaitachi, the weasel-like yokai with sickle-like claws, is known for causing sudden injuries to travelers.",
        "shirime": "Shirime, the eyeless yokai that reveals its featureless rear end when approached, is a humorous but spooky figure.",
        "noppera-bo": "Noppera-bo, the faceless ghost, is a common character in Japanese ghost stories.",
        "ubume": "Ubume, the ghostly mother, is a sorrowful figure often associated with childbirth and maternal love.",
        "akateko": "Akateko, the red hand, is a ghostly hand that dangles from trees to startle passersby.",
        "rakshasa": "Rakshasa, the demon-like beings, appear in various forms across Asian folklore.",
        "rokurokubi": "Rokurokubi, the creatures with the ability to stretch their necks at night, are both spooky and intriguing.",
        "tannuki": "Tannuki, the shape-shifters, are known for their playful and sometimes mischievous nature.",
        "karasu-tengu": "Karasu-tengu, the crow tengu, is a mountain-dwelling yokai with a humanoid appearance.",
        "sodehiki-kozo": "Sodehiki-kozo, the sleeve-pulling boy, is known for tugging on people's sleeves at night, startling them.",
        "gagoze": "Gagoze, a demonic figure, is associated with the legendary warrior Minamoto no Yorimitsu.",
        "inugami": "Inugami, dog spirits, are summoned entities with a connection to dark magic.",
        "isobu": "Isobu, the three-tailed turtle, is one of the tailed beasts in Japanese folklore.",
        "fuji-no-himemiko": "Fuji-no-Himemiko, a kami associated with Mount Fuji, adds a divine touch to Japanese folklore.",
        "tamamo-no-mae": "Tamamo-no-Mae, a cunning kitsune spirit, played a significant role in Japanese history and legend.",
        "kosode-no-te": "Kosode-no-te, the ghostly hand that extends from a kimono sleeve, is a spooky but intriguing figure.",
        "jikininki": "Jikininki, the flesh-eating spirits, are cursed beings who feed on corpses.",
        "menreiki": "Menreiki, a vengeful spirit with a frightening mask, is a chilling presence in Japanese folklore.",
        "kawa-no-kami": "Kawa-no-kami, river deities, are revered for their role in shaping the natural world.",
        "okubi": "Okubi, the big head, is a comical but creepy yokai with a giant head and tiny body.",
        "kusari-gama": "Kusari-gama, the chain-sickle weapon, adds a martial arts element to folklore.",
        "shoki": "Shoki, the demon-queller, is a powerful figure who wards off evil spirits.",
        "furari-bi": "Furari-bi, the swinging fire, is a ghostly light that lures travelers off the beaten path.",
        "akamata": "Akamata, a red-eyed creature, is believed to cause disasters in some Japanese legends.",
        "ikuchi": "Ikuchi, the sea monster with a serpentine body, lurks beneath the waves.",
        "amamehagi": "Amamehagi, the rain-hag, is associated with rainy weather and thunderstorms.",
        "yama-uba": "Yama-uba, the mountain witch, is a formidable and sometimes dangerous figure.",
        "tengu": "Tengu, the bird-like yokai, are known for their martial arts skills and wisdom.",
        "ainu-kamuy": "Ainu-kamuy, the deities of the Ainu people, are a unique part of Japan's folklore.",
        "ashinaga-tenaga": "Ashinaga-tenaga, the long-legged and long-armed yokai, are a memorable sight.",
        "awabi-no-kami": "Awabi-no-kami, the god of abalones, adds a marine touch to Japanese mythology.",
        "shirime": "Shirime, the eyeless yokai that reveals its featureless rear end when approached, is a humorous but spooky figure.",
        "yama-onna": "Yama-onna, the mountain woman, is a ghostly figure associated with remote and rugged terrain.",
        "amikiri": "Amikiri, the net-cutting yokai, is known for slicing through fishermen's nets.",
        "tenjin": "Tenjin, the kami of scholarship and learning, is revered by students and scholars.",
        "hitotsume-kozo": "Hitotsume-kozo, the one-eyed child, is a peculiar and unsettling yokai.",
        "nezumi-kozo": "Nezumi-kozo, the rat boy, is a mischievous and often thieving spirit.",
        "umai-bozu": "Umai-bozu, the sea spirit, is known for its large size and menacing presence.",
        "oni": "Oni, the ogre-like demons, are common figures in Japanese folklore, often depicted with horns and clubs.",
        "tengu mask": "Tengu masks are not only iconic but also believed to ward off evil spirits. Would you like to learn more about their significance?",
        "shojo": "Shojo, the red-faced sake-loving yokai, is associated with celebration and merriment.",
        "itako": "Itako, blind female mediums, are believed to have the ability to communicate with the dead.",
        "wanyudo": "Wanyudo, the flaming cart wheel, is a ghostly presence often seen rolling through the night.",
        "aoandon": "Aoandon, the blue lantern ghost, is a spooky figure that appears with ghost stories.",
        "shirouneri": "Shirouneri, the white thread spirit, is known for tangling people in threads as they walk through forests.",
        "yo-kai": "Yo-kai, a category of supernatural creatures, includes a wide variety of characters.",
        "karasu-tengu": "Karasu-tengu, the crow tengu, is a mountain-dwelling yokai with a humanoid appearance.",
        "akamata": "Akamata, a red-eyed creature, is believed to cause disasters in some Japanese legends.",
        "yama-uba": "Yama-uba, the mountain witch, is a formidable and sometimes dangerous figure.",
        "shirime": "Shirime, the eyeless yokai that reveals its featureless rear end when approached, is a humorous but spooky figure.",
        "rojin": "Rojin, the old man spirit, is often associated with senility and dementia.",
        "tengu": "Tengu, the bird-like yokai, are known for their martial arts skills and wisdom.",
        "kasha": "Kasha, the fiery cart yokai, is a spectral creature associated with death.",
        "goryo": "Goryo, vengeful spirits, are believed to return from the afterlife seeking revenge.",
        "ikuchi": "Ikuchi, the sea monster with a serpentine body, lurks beneath the waves.",
        # Add more specific trigger words and their associated sentences here
            },
            "RandomResponses": [
        "Ah, Japanese folklore! It's filled with fascinating tales of yokai, spirits, and legendary creatures.",
        "Did you know that kitsune are often portrayed as clever and playful shape-shifters?",
        "Japanese mythology is a treasure trove of captivating stories. Would you like to hear more?",
        "Speaking of yokai, some of them are quite mischievous!",
        "Yokai and folklore from Japan are a delightful mix of the supernatural and the mysterious.",
        "The world of Japanese folklore is as rich as it is enchanting.",
        "Each yokai and creature in Japanese folklore has a unique story to tell.",
        "I can't resist sharing more fascinating stories from Japanese folklore!",
        "Let me take you on a journey through the mystical world of Japanese folklore.",
        "Kappa, tengu, and kitsune are just a few of the captivating beings in Japanese mythology.",
        "Japanese folklore is a blend of ancient beliefs, mythical creatures, and timeless tales.",
        "The yokai of Japan come in all shapes and sizes, each with its own quirks and stories.",
        "Intrigued by Japanese folklore? There's always something new to discover!",
        "Prepare to be enchanted by the magical world of Japanese folklore!",
        "The supernatural beings in Japanese folklore are both captivating and mysterious.",
        "The stories of yokai and spirits in Japan are woven into the fabric of its culture.",
        "There's no shortage of fascinating characters in Japanese folklore!",
        "From the mischievous kappa to the wise tengu, Japanese folklore has it all.",
        "Let's dive deeper into the captivating world of Japanese folklore!",
        "The tales of yokai and spirits have been passed down through generations in Japan.",
        "Japanese folklore is a treasure trove of imagination and wonder.",
        "Discover the enchanting world of Japanese folklore, where myths come to life.",
        "Folklore from Japan is filled with colorful characters and intriguing tales.",
        "Japanese mythology is a realm of wonder and mystery, waiting to be explored.",
        "The legends of Japan are as diverse as the country itself, spanning centuries.",
        "Japanese folklore is a fascinating tapestry of myths, legends, and supernatural beings.",
        "The folklore of Japan is a captivating blend of tradition and fantasy.",
        "Delve into the mystical realm of Japanese folklore and uncover its hidden gems.",
        "The spirits and creatures of Japanese folklore are both captivating and enigmatic.",
        "Step into the world of Japanese folklore, where the ordinary becomes extraordinary.",
        "The folklore of Japan is a world of wonder, where the supernatural meets the mundane.",
        "Every yokai and creature in Japanese folklore has a unique story to tell.",
        "Japanese folklore is a magical journey through the rich tapestry of Japan's cultural heritage.",
        "Explore the enchanting world of Japanese folklore, where legends come to life.",
        "Japanese mythology is a treasure trove of captivating stories and timeless wisdom.",
        "The tales of yokai and spirits in Japan are woven into the fabric of its culture.",
        "Prepare to be enchanted by the mesmerizing world of Japanese folklore!",
        "The supernatural beings of Japanese folklore are both mysterious and captivating.",
        "Intrigued by Japanese folklore? Let's embark on a journey of discovery!",
        "Japanese folklore is a realm of imagination and wonder, waiting to be explored.",
        "Uncover the hidden treasures of Japanese folklore as we venture deeper into its mysteries.",
        "Folklore from Japan is a captivating blend of tradition and fantasy.",
        "Japanese mythology is a world where myths and reality intertwine, creating a rich tapestry of stories.",
        "The folklore of Japan is a fascinating exploration of culture, beliefs, and the unknown.",
        "Japanese folklore is a journey through time, where ancient tales still resonate today.",
        "The spirits and creatures of Japanese folklore invite us into a world of mystery and wonder.",
        "Step into the realm of Japanese folklore and discover the magic within its stories.",
        "Explore the enchanting world of Japanese folklore, where legends come alive.",
        "Japanese mythology is a realm of endless possibilities, where imagination knows no bounds.",
        "The tales of yokai and spirits in Japan are a testament to the country's cultural richness.",
        "Japanese folklore is a mosaic of myths, legends, and creatures from a bygone era.",
        "Prepare to be captivated by the mesmerizing world of Japanese folklore!",
        "Intrigued by the supernatural? Japanese folklore offers a captivating journey.",
        "Japanese folklore is a universe of enchanting stories that continue to inspire.",
        "The folklore of Japan is a tapestry of tradition and fantasy, woven through generations.",
        "Japanese mythology is a treasure chest filled with gems of wisdom and wonder.",
        "Uncover the hidden treasures of Japanese folklore as we explore its vibrant tapestry.",
        "The spirits and creatures of Japanese folklore beckon us into a world of enchantment and intrigue.",
        "Japanese folklore is a doorway to a realm where the extraordinary is the norm.",
        "Let's embark on a journey through the captivating world of Japanese folklore!",
        "Japanese mythology is a vibrant mosaic of stories that have shaped a nation's identity.",
        "The tales of yokai and spirits in Japan are a testament to the country's rich storytelling tradition.",
        "Japanese folklore is a timeless treasure trove of imagination, culture, and wonder.",
        "Prepare to be spellbound by the mesmerizing world of Japanese folklore!",
        "Intrigued by the supernatural? Japanese folklore offers endless fascination and mystery.",
        "Japanese folklore is a boundless universe of enchanting tales and mythical beings.",
        "The folklore of Japan is a bridge between the past and the present, where legends endure.",
        "Japanese mythology is a living legacy of stories that continue to captivate hearts.",
        "Uncover the hidden gems of Japanese folklore as we delve deeper into its mysteries.",
        "The spirits and creatures of Japanese folklore invite us to explore a world of magic and wonder.",
        "Japanese folklore is a doorway to a realm where legends come to life.",
        "Let's journey through the captivating world of Japanese folklore, where myths are reborn.",
        "Japanese mythology is a vibrant mosaic of stories that reflect the soul of a nation.",
        "The tales of yokai and spirits in Japan are a window into the country's cultural heritage.",
        "Japanese folklore is a timeless treasure trove of imagination, tradition, and awe.",
        "Prepare to be entranced by the enchanting world of Japanese folklore!",
            ]
        },
        # Add more trigger words and responses as needed
    }
    return vocab_data